// @ts-check
/**
 * Mark 2 OpSet surface — every Move/Join mode and the edge cases that
 * previously regressed.
 */

/** @typedef {import('./harness.mjs').Case} Case */

/** @type {Case[]} */
export const MARK2_CASES = [
  // --- edge wrap ---
  {
    id: "wrap-h-a-left",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Select(A)", "Move(left)"],
    expect: "Mon1(H(B,A))",
    expectMode: "wrap",
  },
  {
    id: "wrap-h-b-right",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Select(B)", "Move(right)"],
    expect: "Mon1(H(B,A))",
    expectMode: "wrap",
  },
  {
    id: "wrap-tab-a-left",
    layer: "opset",
    given: "Mon1(TAB(A,B))",
    actions: ["Select(A)", "Move(left)"],
    expect: "Mon1(TAB(B,A))",
    expectMode: "wrap",
  },
  {
    id: "wrap-stack-b-right",
    layer: "opset",
    given: "Mon1(STACK(A,B))",
    actions: ["Select(B)", "Move(right)"],
    expect: "Mon1(STACK(B,A))",
    expectMode: "wrap",
  },
  {
    id: "wrap-v-a-up",
    layer: "opset",
    given: "Mon1(V(A,B))",
    actions: ["Select(A)", "Move(up)"],
    expect: "Mon1(V(B,A))",
    expectMode: "wrap",
  },
  {
    id: "wrap-h-n3-rotate",
    layer: "opset",
    given: "Mon1(H(A,B,C))",
    actions: ["Select(A)", "Move(left)"],
    expect: "Mon1(H(B,C,A))",
    expectMode: "wrap",
  },
  {
    id: "wrap-h-n3-c-right",
    layer: "opset",
    given: "Mon1(H(A,B,C))",
    actions: ["Select(C)", "Move(right)"],
    expect: "Mon1(H(C,A,B))",
    expectMode: "wrap",
  },
  {
    id: "wrap-before-crossmon-b-right",
    layer: "opset",
    given: "Mon1(H(A,B)) Mon2(H(C,D))",
    actions: ["Select(B)", "Move(right)"],
    expect: "Mon1(H(B,A)) Mon2(H(C,D))",
    expectMode: "wrap",
    note: "wrap beats cross-mon absorb",
  },
  {
    id: "wrap-before-crossmon-a-left",
    layer: "opset",
    given: "Mon1(H(A,B)) Mon2(H(C,D))",
    actions: ["Select(A)", "Move(left)"],
    expect: "Mon1(H(B,A)) Mon2(H(C,D))",
    expectMode: "wrap",
  },

  // --- swap (non-edge) ---
  {
    id: "swap-h-a-right",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Select(A)", "Move(right)"],
    expect: "Mon1(H(B,A))",
    expectMode: "swap",
  },
  {
    id: "swap-h-n3-middle",
    layer: "opset",
    given: "Mon1(H(A,B,C))",
    actions: ["Select(B)", "Move(right)"],
    expect: "Mon1(H(A,C,B))",
    expectMode: "swap",
  },
  {
    id: "swap-v-a-down",
    layer: "opset",
    given: "Mon1(V(A,B))",
    actions: ["Select(A)", "Move(down)"],
    expect: "Mon1(V(B,A))",
    expectMode: "swap",
  },
  {
    id: "swap-tab-a-right",
    layer: "opset",
    given: "Mon1(TAB(A,B,C))",
    actions: ["Select(A)", "Move(right)"],
    expect: "Mon1(TAB(B,A,C))",
    expectMode: "swap",
  },

  // --- join: mon sole-child any-dir wrap-pair ---
  {
    id: "join-mon-v-any-left",
    layer: "opset",
    given: "Mon1(V(A,B))",
    actions: ["Select(A)", "Join(left)"],
    expect: "Mon1(H(A,B))",
    expectMode: "wrap-pair",
  },
  {
    id: "join-mon-v-toward",
    layer: "opset",
    given: "Mon1(V(A,B))",
    actions: ["Select(A)", "Join(down)"],
    expect: "Mon1(H(A,B))",
    expectMode: "wrap-pair",
  },
  {
    id: "join-mon-h-any-up",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Select(A)", "Join(up)"],
    expect: "Mon1(V(A,B))",
    expectMode: "wrap-pair",
  },
  {
    id: "join-mon-h-any-down",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Select(A)", "Join(down)"],
    expect: "Mon1(V(A,B))",
    expectMode: "wrap-pair",
  },

  // --- join: nested edge breakout + cross-axis promote ---
  {
    id: "join-nested-c-left-promote",
    layer: "opset",
    given: "Mon1(H(V(A,B),V(C,D)))",
    actions: ["Select(C)", "Join(left)"],
    expect: "Mon1(H(A,B,C,D))",
    expectMode: /breakout-promote-join/,
  },
  {
    id: "join-nested-a-right-promote",
    layer: "opset",
    given: "Mon1(H(V(A,B),V(C,D)))",
    actions: ["Select(A)", "Join(right)"],
    expect: "Mon1(H(B,A,C,D))",
    expectMode: /breakout-promote-join/,
  },
  {
    id: "join-nested-c-down-wrap-pair",
    layer: "opset",
    given: "Mon1(H(V(A,B),V(C,D)))",
    actions: ["Select(C)", "Join(down)"],
    expect: "Mon1(H(V(A,B),TAB(C,D)))",
    expectMode: "wrap-pair",
  },
  {
    id: "join-nested-d-up-wrap-pair",
    layer: "opset",
    given: "Mon1(H(V(A,B),V(C,D)))",
    actions: ["Select(D)", "Join(up)"],
    expect: "Mon1(H(V(A,B),TAB(D,C)))",
    expectMode: "wrap-pair",
    note: "wrap order is selected leaf then sibling",
  },

  // --- join: emptied TAB invents vs host ---
  {
    id: "join-tab-under-h-invent-v",
    layer: "opset",
    given: "Mon1(H(A,TAB(B,C)))",
    actions: ["Select(B)", "Join(right)"],
    expect: "Mon1(H(A,V(B,C)))",
    expectMode: "wrap-pair",
  },
  {
    id: "join-tab-under-v-invent-h",
    layer: "opset",
    given: "Mon1(V(A,TAB(B,C)))",
    actions: ["Select(B)", "Join(right)"],
    expect: "Mon1(V(A,H(B,C)))",
    expectMode: "wrap-pair",
  },

  // --- join enter-con ---
  {
    id: "join-enter-tab-from-left",
    layer: "opset",
    given: "Mon1(H(A,TAB(B,C)))",
    actions: ["Select(A)", "Join(right)"],
    expect: "Mon1(TAB(A,B,C))",
    expectMode: /enter-con/,
    note: "enter at near edge of TAB (start), then unary H collapses",
  },
  {
    id: "join-tab-into-left-tab",
    layer: "opset",
    given: "Mon1(H(TAB(A,B),TAB(C,D)))",
    actions: ["Select(C)", "Join(left)"],
    expect: "Mon1(H(TAB(A,B,C),D))",
    expectMode: /breakout-enter-con/,
    note: "C joins TAB(A,B) at the near (right) edge; D stays after unary",
  },
  {
    id: "joinmove-tab-into-left-tab",
    layer: "opset",
    given: "Mon1(H(TAB(A,B),TAB(C,D)))",
    actions: ["JoinMove(C, left)"],
    expect: "Mon1(H(TAB(A,B,C),D))",
    expectMode: /breakout-enter-con/,
  },
  {
    id: "join-tab-into-right-tab",
    layer: "opset",
    given: "Mon1(H(TAB(A,B),TAB(C,D)))",
    actions: ["Select(B)", "Join(right)"],
    expect: "Mon1(H(A,TAB(B,C,D)))",
    expectMode: /breakout-enter-con/,
  },
  {
    id: "join-three-toward-window",
    layer: "opset",
    given: "Mon1(H(A,B,C))",
    actions: ["Select(B)", "Join(right)"],
    expect: "Mon1(H(A,V(B,C)))",
    expectMode: "wrap-pair",
  },

  // --- move breakout ---
  {
    id: "move-breakout-nested-left",
    layer: "opset",
    given: "Mon1(H(V(A,B),C))",
    actions: ["Select(A)", "Move(left)"],
    expect: "Mon1(H(A,B,C))",
    expectMode: "breakout",
    note: "cross-axis breakout + unary V(B)",
  },
  {
    id: "move-breakout-nested-right",
    layer: "opset",
    given: "Mon1(H(V(A,B),C))",
    actions: ["Select(B)", "Move(right)"],
    expect: "Mon1(H(A,B,C))",
    expectMode: "breakout",
  },

  // --- cross-mon when wrap cannot apply ---
  {
    id: "move-crossmon-sole-window",
    layer: "opset",
    given: "Mon1(A) Mon2(B)",
    actions: ["Select(A)", "Move(right)"],
    expect: "Mon1() Mon2(V(A,B))",
    expectMode: "cross-mon",
  },

  // --- toggle / promote ---
  {
    id: "toggle-split-h-to-v",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Select(A)", "ToggleSplit()"],
    expect: "Mon1(V(A,B))",
  },
  {
    id: "toggle-tab-from-h",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Select(A)", "ToggleTabStack()"],
    expect: "Mon1(TAB(A,B))",
  },
  {
    id: "promote-nested-v",
    layer: "opset",
    given: "Mon1(H(V(A,B),C))",
    actions: ["Select(A)", "SelectParent()", "Promote()"],
    expect: "Mon1(H(A,B,C))",
  },
  {
    id: "promote-mon-sole-child-refused",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Select(A)", "SelectParent()", "Promote()"],
    expect: "Mon1(H(A,B))",
    expectOk: false,
  },

  // --- remove settle ---
  {
    id: "remove-collapses-unary",
    layer: "opset",
    given: "Mon1(H(V(A,B),C))",
    actions: ["Select(B)", "Remove()"],
    expect: "Mon1(H(A,C))",
  },
  {
    id: "delete-atomic-leaves-unary",
    layer: "opset",
    given: "Mon1(H(V(A,B),C))",
    actions: ["Select(B)", "Delete()"],
    expect: "Mon1(H(V(A),C))",
    note: "TreeOp destroy does not run OpSet settle",
  },

  // --- Launch (1920×1080 default geom) ---
  {
    id: "launch-empty-monitor",
    layer: "opset",
    given: "Mon1()",
    actions: ["Launch()"],
    expect: "Mon1(A)",
    expectMode: "empty",
  },
  {
    id: "launch-end-hsplit",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Launch()"],
    expect: "Mon1(H(A,B,C))",
    expectMode: "sibling",
  },
  {
    id: "launch-end-vsplit",
    layer: "opset",
    given: "Mon1(V(A,B))",
    actions: ["Launch()"],
    expect: "Mon1(V(A,B,C))",
    expectMode: "sibling",
  },
  {
    id: "launch-tab-next-sibling",
    layer: "opset",
    given: "Mon1(TAB(A,B))",
    actions: ["Select(A)", "Launch()"],
    expect: "Mon1(TAB(A,C,B))",
    expectMode: "sibling",
  },
  {
    id: "launch-stack-next-sibling",
    layer: "opset",
    given: "Mon1(STACK(A,B))",
    actions: ["Select(B)", "Launch()"],
    expect: "Mon1(STACK(A,B,C))",
    expectMode: "sibling",
  },
  {
    id: "launch-h-taller-wrap-v",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Select(A)", "Launch()"],
    expect: "Mon1(H(V(A,C),B))",
    expectMode: "wrap-split",
    note: "960×1080 taller than wide → VSPLIT wrap",
  },
  {
    id: "launch-h-select-b-wrap-v",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Select(B)", "Launch()"],
    expect: "Mon1(H(A,V(B,C)))",
    expectMode: "wrap-split",
  },
  {
    id: "launch-v-wider-wrap-h",
    layer: "opset",
    given: "Mon1(V(A,B))",
    actions: ["Select(A)", "Launch()"],
    expect: "Mon1(V(H(A,C),B))",
    expectMode: "wrap-split",
    note: "1920×540 wider than tall → HSPLIT wrap",
  },
  {
    id: "launch-sole-window-wrap-h",
    layer: "opset",
    given: "Mon1(A)",
    actions: ["Select(A)", "Launch()"],
    expect: "Mon1(H(A,B))",
    expectMode: "wrap-split",
  },
  {
    id: "launch-h-wider-next-sibling",
    layer: "opset",
    given: "Mon1(H(A,B))",
    run(t) {
      t.api.setFocus(t.f, t.win("A").id);
      const r = t.api.setInAxisShare(t.f, 0.6);
      if (!r.ok) return r.reason;
    },
    actions: ["Select(A)", "Launch()"],
    expect: "Mon1(H(A,C,B))",
    expectMode: "sibling",
    note: "0.6×1920=1152 > 1080 → sibling in H",
  },
  {
    id: "launch-h-min-fallback-tab",
    layer: "opset",
    given: "Mon1(H(A,B))",
    run(t) {
      t.api.setFocus(t.f, t.win("A").id);
      const r = t.api.setInAxisShare(t.f, 0.85);
      if (!r.ok) return r.reason;
    },
    actions: ["Select(A)", "Launch()"],
    expect: "Mon1(H(TAB(A,C),B))",
    expectMode: "wrap-tab",
    note: "wider than tall but leftover 15% / 2 floaters < 10%",
  },
  {
    id: "launch-end-ten-kids-tab",
    layer: "opset",
    given: "Mon1(H(A,B,C,D,E,F,G,H,I,J))",
    actions: ["Launch()"],
    expect: "Mon1(H(A,B,C,D,E,F,G,H,I,TAB(J,K)))",
    expectMode: "wrap-tab",
  },
  {
    id: "launch-other-mon-is-end",
    layer: "opset",
    given: "Mon1(H(A,B)) Mon2(H(C,D))",
    actions: ["Select(A)", "Launch(Mon2)"],
    expect: "Mon1(H(A,B)) Mon2(H(C,D,E))",
    expectMode: "sibling",
  },
  {
    id: "launch-nested-v-child-wrap-h",
    layer: "opset",
    given: "Mon1(H(V(A,B),C))",
    actions: ["Select(A)", "Launch()"],
    expect: "Mon1(H(V(H(A,D),B),C))",
    expectMode: "wrap-split",
    note: "A is 960×540 (wider) in V → wrap H",
  },
  {
    id: "launch-select-tab-parent-wrap-v",
    layer: "opset",
    given: "Mon1(H(TAB(A,B),C))",
    actions: ["Select(A)", "SelectParent()", "Launch()"],
    expect: "Mon1(H(V(TAB(A,B),D),C))",
    expectMode: "wrap-split",
    note: "Selected TAB is 960×1080 (taller) in H → wrap V; D is bottom-left",
  },
  {
    id: "launch-select-stack-parent-wrap-v",
    layer: "opset",
    given: "Mon1(H(STACK(A,B),C))",
    actions: ["Select(A)", "SelectParent()", "Launch()"],
    expect: "Mon1(H(V(STACK(A,B),D),C))",
    expectMode: "wrap-split",
  },
  {
    id: "launch-select-tab-on-mon-wrap-h",
    layer: "opset",
    given: "Mon1(TAB(A,B))",
    actions: ["Select(A)", "SelectParent()", "Launch()"],
    expect: "Mon1(H(TAB(A,B),C))",
    expectMode: "wrap-split",
    note: "Selected TAB fills 1920×1080 (wider) → wrap H, not a third tab",
  },
  {
    id: "launch-select-h-on-mon-opposite-v",
    layer: "opset",
    given: "Mon1(H(A,B))",
    actions: ["Select(A)", "SelectParent()", "Launch()"],
    expect: "Mon1(V(H(A,B),C))",
    expectMode: "wrap-split",
    note: "Wrap H around H would same-type; MONITOR uses opposite V",
  },
  {
    id: "launch-select-v-inserts-into-v",
    layer: "opset",
    given: "Mon1(H(V(A,B),C))",
    actions: ["Select(A)", "SelectParent()", "Launch()"],
    expect: "Mon1(H(V(A,B,D),C))",
    expectMode: "sibling",
    note: "Wrap V around V would same-type; insert as last child of V",
  },
  {
    id: "launch-con-on-other-mon-is-end",
    layer: "opset",
    given: "Mon1(H(TAB(A,B),C)) Mon2(H(D,E))",
    actions: ["Select(A)", "SelectParent()", "Launch(Mon2)"],
    expect: "Mon1(H(TAB(A,B),C)) Mon2(H(D,E,F))",
    expectMode: "sibling",
  },
];
