/*
 * This file is part of the Forge extension for GNOME
 *
 * Portable GSettings key allowlists (config-sync + FC3 settings control).
 * Kept free of Gio/GObject so pure helpers can import without circular deps.
 */

// Settings keys that should be synced to settings.json
export const SETTINGS_KEYS = {
  behavior: [
    "tiling-mode-enabled",
    "focus-on-hover-enabled",
    "move-pointer-focus-enabled",
    "auto-split-enabled",
    "tiny-pane-tab-fallback-enabled",
    "tiny-pane-min-edge",
    "stacked-tiling-mode-enabled",
    "tabbed-tiling-mode-enabled",
    "auto-exit-tabbed",
    "auto-reorient-on-close",
    "default-window-layout",
    "dnd-center-layout",
    "float-always-on-top-enabled",
    "auto-unmaximize-for-tiling",
    "focus-on-hover-tiling-only",
    "disable-edge-tiling",
    "new-window-placement",
    "new-window-size-policy",
  ],
  appearance: [
    "focus-border-toggle",
    "focus-border-radius",
    "split-border-toggle",
    "window-gap-size",
    "window-gap-size-increment",
    "window-gap-hidden-on-single",
    "window-maximize-on-single",
    "focus-border-hidden-on-single",
    "window-margin-top",
    "window-margin-bottom",
    "window-margin-left",
    "window-margin-right",
    "preview-hint-enabled",
    "showtab-decoration-enabled",
    "tabbed-tab-margin",
    "stacked-tab-bar-height",
    "max-tabs-per-line",
    "tab-position",
    "quick-settings-enabled",
    "tray-icon-enabled",
  ],
  workspaces: ["workspace-skip-tile", "monitor-skip-tile"],
  development: ["log-level", "logging-enabled", "layout-debug-overlay-enabled"],
  other: ["resize-amount", "launch-app-command"],
};

// Keybinding keys that should be synced
export const KEYBINDING_KEYS = [
  "focus-border-toggle",
  "window-gap-size-increase",
  "window-gap-size-decrease",
  "con-split-layout-toggle",
  "con-split-horizontal",
  "con-split-vertical",
  "con-stacked-layout-toggle",
  "con-tabbed-layout-toggle",
  "con-tabbed-showtab-decoration-toggle",
  "window-swap-left",
  "window-swap-down",
  "window-swap-up",
  "window-swap-right",
  "window-move-left",
  "window-move-down",
  "window-move-up",
  "window-move-right",
  "window-focus-left",
  "window-focus-down",
  "window-focus-up",
  "window-focus-right",
  "window-toggle-float",
  "window-toggle-always-float",
  "workspace-active-tile-toggle",
  "prefs-open",
  "prefs-tiling-toggle",
  "window-swap-last-active",
  "window-focus-next",
  "window-focus-prev",
  "window-swap-next",
  "window-swap-prev",
  "window-snap-one-third-right",
  "window-snap-two-third-right",
  "window-snap-one-third-left",
  "window-snap-two-third-left",
  "window-snap-center",
  "window-resize-left-increase",
  "window-resize-left-decrease",
  "window-resize-bottom-increase",
  "window-resize-bottom-decrease",
  "window-resize-top-increase",
  "window-resize-top-decrease",
  "window-resize-right-increase",
  "window-resize-right-decrease",
  "window-reset-sizes",
  "window-golden-ratio",
  "prefs-config-reload",
  "prefs-config-export",
  "window-pointer-to-focus",
  "workspace-monocle-toggle",
  "window-expand",
  "window-shrink",
  "prefs-app-launch",
  "prefs-cheatsheet-toggle",
  "prefs-lock-screen",
  "layout-debug-overlay-toggle",
];

// The mod-mask-mouse-tile key is a string, not an array
export const KEYBINDING_STRING_KEYS = ["mod-mask-mouse-tile"];
