export const developers = [
  "Jose Maranan <jmmaranan@gmail.com>",
  "Jon Crussell <joncrussell@gmail.com>",
  "Benny Powers <web@bennypowers.com>",
  "Juarez Rudsatz <juarezr@gmail.com>",
  "Juarez Rudsatz <juarezrudsatz@movida.com.br>",
  "PhilippKosarev <philipp.kosarev@gmail.com>",
  "Eskander Bejaoui <mail@eskander.tn>",
  "S1m <git@sgougeon.fr>",
  "Andrew Kvalheim <andrew@kvalhe.im>",
  "Ted M Lin <tedmlin@gmail.com>",
  "Alexander Kolenaty <akolenaty@protonmail.ch>",
  "Azakidev <zazaguichi@outlook.com>",
  "Heimen Stoffels <vistausss@fastmail.com>",
  "Alesya Huzik <public@aguzik.net>",
  "Amir Fazleev <hello@AmirFazleev.ru>",
  "Carl George <carlwgeorge@gmail.com>",
  "Christopher Harrison <cnharrison@gmail.com>",
  "Craig Gross <craig@c-gross.net>",
  "Grant Ammons <gammons@gmail.com>",
  "Luca Pattocchio <pattocchioluca@gmail.com>",
  "Matt Barry <matt@hazelmollusk.org>",
  "Mucahit Sahin <mucahitsahin786@gmail.com>",
  "RedHare-Exe <redgrappler18@gmail.com>",
  "William Roy <wroy@proton.me>",
  "Yevhen Popok <xalt7x.service@gmail.com>",
  "aZero <fr.rodmar@gmail.com>",
  "crimist <git@crim.ist>",
  "matdave <mat@matdave.com>",
];
