#!/usr/bin/env zsh
# Shared helpers for scripts/forge/*.zsh — source only, not run directly.
emulate -L zsh
set -euo pipefail

FORGE_UUID="${FORGE_UUID:-forge@jmmaranan.com}"
FORGE_SCHEMA_MAIN="${FORGE_SCHEMA_MAIN:-org.gnome.shell.extensions.forge}"
FORGE_SCHEMA_KBD="${FORGE_SCHEMA_KBD:-org.gnome.shell.extensions.forge.keybindings}"
FORGE_DCONF_PATH="${FORGE_DCONF_PATH:-/org/gnome/shell/extensions/forge/}"
FORGE_EXT_DIR="${FORGE_EXT_DIR:-$HOME/.local/share/gnome-shell/extensions/$FORGE_UUID}"
FORGE_CONFIG_DIR="${FORGE_CONFIG_DIR:-$HOME/.config/forge}"
FORGE_BACKUP_ROOT="${FORGE_BACKUP_ROOT:-$HOME/.local/share/forge-manage/backups}"
FORGE_EGO_UUID="${FORGE_EGO_UUID:-$FORGE_UUID}"
FORGE_EGO_API="${FORGE_EGO_API:-https://extensions.gnome.org/extension-info/}"
FORGE_EGO_BASE="${FORGE_EGO_BASE:-https://extensions.gnome.org}"

# Repo root: this file lives at scripts/forge/_lib.zsh
# (do not assign to $0 — it breaks command lookup in some zsh builds)
_forge_lib_file=${(%):-%N}
FORGE_SCRIPTS_DIR="${FORGE_SCRIPTS_DIR:-${_forge_lib_file:A:h}}"
FORGE_REPO_ROOT="${FORGE_REPO_ROOT:-${FORGE_SCRIPTS_DIR:h:h}}"
unset _forge_lib_file

FORGE_VERSION="1.0.0"
FORGE_COLOR="${FORGE_COLOR:-auto}"

# --- ANSI ---
_forge_use_color() {
  case "$FORGE_COLOR" in
    always) return 0 ;;
    never) return 1 ;;
    auto|*) [[ -t 1 ]] && [[ -t 0 || ! -p /dev/stdout ]] ;;
  esac
}

if _forge_use_color; then
  c_reset=$'\e[0m'
  c_bold=$'\e[1m'
  c_red=$'\e[31m'
  c_green=$'\e[32m'
  c_yellow=$'\e[33m'
  c_blue=$'\e[34m'
  c_magenta=$'\e[35m'
  c_cyan=$'\e[36m'
else
  c_reset= c_bold= c_red= c_green= c_yellow= c_blue= c_magenta= c_cyan=
fi

forge_die() { print -u2 -- "${c_red}forge: $*${c_reset}"; exit 1; }
forge_warn() { print -u2 -- "${c_yellow}forge: $*${c_reset}"; }
forge_info() { print -u2 -- "${c_cyan}forge: $*${c_reset}"; }
forge_ok() { print -u2 -- "${c_green}forge: $*${c_reset}"; }
forge_hdr() { print -u2 -- "${c_magenta}${c_bold}$*${c_reset}"; }

forge_is_tty() { [[ -t 0 && -t 1 ]]; }

forge_confirm() {
  # $1 prompt; default yes unless FORGE_CONFIRM_DEFAULT=no
  local prompt="$1" def="${FORGE_CONFIRM_DEFAULT:-yes}" ans
  if ! forge_is_tty; then
    [[ "${FORGE_FORCE:-0}" == "1" ]] && return 0
    forge_die "non-interactive; pass --force or set FORGE_FORCE=1 ($prompt)"
  fi
  local hint="[Y/n]"
  [[ "$def" == "no" ]] && hint="[y/N]"
  print -n -- "${c_yellow}$prompt $hint ${c_reset}"
  read -r ans || ans=""
  ans="${ans:l}"
  if [[ -z "$ans" ]]; then
    [[ "$def" == "yes" ]] && return 0 || return 1
  fi
  [[ "$ans" == "y" || "$ans" == "yes" ]]
}

forge_need_cmd() {
  local c
  for c in "$@"; do
    command -v "$c" >/dev/null 2>&1 || {
      print -u2 -- "${c_red}forge: \`$c\` not found${c_reset}"
      print -u2 -- "Install the missing tool, then re-run."
      exit 127
    }
  done
}

forge_stamp() { date +%Y%m%d-%H%M%S; }

forge_shell_version() {
  # major only, e.g. 46
  local v
  v=$(gnome-shell --version 2>/dev/null | grep -oE '[0-9]+' | head -1) || true
  print -r -- "${v:-46}"
}

forge_session_type() {
  print -r -- "${XDG_SESSION_TYPE:-unknown}"
}

forge_ext_installed() {
  [[ -d "$FORGE_EXT_DIR" && -f "$FORGE_EXT_DIR/metadata.json" ]]
}

forge_ext_enabled() {
  gnome-extensions list --enabled 2>/dev/null | grep -qx "$FORGE_UUID"
}

forge_metadata_field() {
  # $1 field name from metadata.json of installed extension
  # NOTE: never name a local `path` — zsh ties path[] ↔ PATH.
  local field="$1" meta="${2:-$FORGE_EXT_DIR/metadata.json}"
  [[ -f "$meta" ]] || return 1
  python3 -c '
import json, sys
from pathlib import Path
p, k = sys.argv[1], sys.argv[2]
try:
    d = json.loads(Path(p).read_text())
except Exception:
    sys.exit(1)
v = d.get(k, "")
if isinstance(v, list):
    print(",".join(str(x) for x in v))
else:
    print("" if v is None else v)
' "$meta" "$field"
}

forge_detect_lineage() {
  # ego | jcrussell | unknown
  # Prefer version-name (git describe stamped by this tree's make build).
  # EGO/SweetTooth stamps numeric "version" and often "_generated".
  # Note: both trees may have lib/extension — do not use layout alone.
  local meta="$FORGE_EXT_DIR/metadata.json" version_name version
  forge_ext_installed || { print -r -- "none"; return 0; }
  version_name=$(forge_metadata_field version-name "$meta" 2>/dev/null || true)
  if [[ -n "$version_name" ]]; then
    print -r -- "jcrussell"
    return 0
  fi
  if grep -q 'Generated by SweetTooth' "$meta" 2>/dev/null; then
    print -r -- "ego"
    return 0
  fi
  version=$(forge_metadata_field version "$meta" 2>/dev/null || true)
  if [[ -n "$version" && "$version" == <-> ]]; then
    print -r -- "ego"
    return 0
  fi
  print -r -- "unknown"
}

forge_schema_dir() {
  local d="$FORGE_EXT_DIR/schemas"
  [[ -d "$d" ]] && print -r -- "$d" && return 0
  d="$FORGE_REPO_ROOT/schemas"
  [[ -d "$d" ]] && print -r -- "$d" && return 0
  return 1
}

forge_with_schema() {
  # run command with GSETTINGS_SCHEMA_DIR pointing at forge schemas
  local sd
  sd=$(forge_schema_dir) || forge_die "no schemas dir (install forge or use repo schemas/)"
  GSETTINGS_SCHEMA_DIR="$sd" "$@"
}

forge_latest_backup() {
  local d
  [[ -d "$FORGE_BACKUP_ROOT" ]] || return 1
  d=$(ls -1d "$FORGE_BACKUP_ROOT"/*/ 2>/dev/null | sort | tail -1) || return 1
  [[ -n "$d" ]] || return 1
  print -r -- "${d%/}"
}

forge_write_meta() {
  # $1 backup dir
  local dest="$1"
  python3 - "$dest" <<'PY'
import json, os, platform, subprocess, sys, time
from pathlib import Path
dest = Path(sys.argv[1])
meta_path = dest / "meta.json"
ext_meta = Path(os.path.expanduser("~/.local/share/gnome-shell/extensions/forge@jmmaranan.com/metadata.json"))
installed = {}
if ext_meta.is_file():
    try:
        installed = json.loads(ext_meta.read_text())
    except Exception:
        pass
shell = ""
try:
    shell = subprocess.check_output(["gnome-shell", "--version"], text=True).strip()
except Exception:
    pass
lineage = "unknown"
if (dest / "meta.lineage").is_file():
    lineage = (dest / "meta.lineage").read_text().strip()
data = {
    "created_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
    "host": platform.node(),
    "user": os.environ.get("USER", ""),
    "session_type": os.environ.get("XDG_SESSION_TYPE", ""),
    "gnome_shell": shell,
    "uuid": "forge@jmmaranan.com",
    "lineage": lineage,
    "installed_metadata": {
        "version": installed.get("version"),
        "version-name": installed.get("version-name"),
        "url": installed.get("url"),
        "shell-version": installed.get("shell-version"),
    },
    "paths": {
        "extension": str(Path.home() / ".local/share/gnome-shell/extensions/forge@jmmaranan.com"),
        "config": str(Path.home() / ".config/forge"),
        "dconf": "/org/gnome/shell/extensions/forge/",
    },
}
meta_path.write_text(json.dumps(data, indent=2) + "\n")
print(meta_path)
PY
}

# Keys present only on EGO (or old upstream) that jcrussell dropped or renamed.
# Values: note for translate report; empty means drop with no remap.
typeset -gA FORGE_KEY_TRANSLATE_NOTES=(
  [focus-border-size]="EGO gsetting removed; use Appearance prefs / CSS in jcrussell"
  [focus-border-color]="EGO gsetting removed; use Appearance prefs / CSS in jcrussell"
  [split-border-color]="EGO gsetting removed; use Appearance prefs / CSS in jcrussell"
  [primary-layout-mode]="EGO key; jcrussell uses tiling-mode-enabled + default-window-layout"
)

forge_schema_keys_from_xml() {
  # print key names from a gschema xml (both main + keybindings if in file)
  local xml="$1"
  [[ -f "$xml" ]] || return 1
  grep -oE 'name="[^"]+"' "$xml" | sed 's/name="//;s/"$//' | sort -u
}

forge_target_schema_keys() {
  # $1 optional: ego|jcrussell|path-to-xml|installed
  local target="${1:-installed}"
  local xml=""
  case "$target" in
    installed)
      xml="$FORGE_EXT_DIR/schemas/org.gnome.shell.extensions.forge.gschema.xml"
      ;;
    jcrussell|dev|repo)
      xml="$FORGE_REPO_ROOT/schemas/org.gnome.shell.extensions.forge.gschema.xml"
      ;;
    ego)
      # Prefer live EGO install if still present; else use forge_original if available
      if [[ -f "$FORGE_EXT_DIR/schemas/org.gnome.shell.extensions.forge.gschema.xml" ]] \
        && [[ "$(forge_detect_lineage)" == "ego" ]]; then
        xml="$FORGE_EXT_DIR/schemas/org.gnome.shell.extensions.forge.gschema.xml"
      elif [[ -f "$HOME/dev/me/forge_original/schemas/org.gnome.shell.extensions.forge.gschema.xml" ]]; then
        xml="$HOME/dev/me/forge_original/schemas/org.gnome.shell.extensions.forge.gschema.xml"
      else
        forge_die "no EGO schema available (install EGO forge or clone forge_original)"
      fi
      ;;
    *)
      if [[ -f "$target" ]]; then
        xml="$target"
      else
        forge_die "unknown schema target: $target"
      fi
      ;;
  esac
  [[ -f "$xml" ]] || forge_die "schema xml not found: $xml"
  forge_schema_keys_from_xml "$xml"
}

forge_parse_common_args() {
  # Consume shared flags; leave command-specific opts/args in FORGE_ARGS.
  # Unknown --flags are NOT rejected here (each script validates its own).
  FORGE_ARGS=()
  FORGE_WANT_HELP=0
  while (( $# )); do
    case "$1" in
      -h|--help) FORGE_WANT_HELP=1; shift ;;
      -V|--version) print -r -- "forge-manage $FORGE_VERSION"; exit 0 ;;
      --force) FORGE_FORCE=1; shift ;;
      --color=*) FORGE_COLOR="${1#--color=}"; shift ;;
      --color)
        [[ -n "${2:-}" ]] || forge_die "--color needs a value"
        FORGE_COLOR="$2"; shift 2
        ;;
      --backup-root=*) FORGE_BACKUP_ROOT="${1#--backup-root=}"; shift ;;
      --backup-root)
        [[ -n "${2:-}" ]] || forge_die "--backup-root needs a value"
        FORGE_BACKUP_ROOT="$2"; shift 2
        ;;
      --repo=*) FORGE_REPO_ROOT="${1#--repo=}"; shift ;;
      --repo)
        [[ -n "${2:-}" ]] || forge_die "--repo needs a value"
        FORGE_REPO_ROOT="$2"; shift 2
        ;;
      --) shift; FORGE_ARGS+=("$@"); break ;;
      *)
        FORGE_ARGS+=("$1"); shift ;;
    esac
  done
}

forge_print_deps_help() {
  cat <<'EOF'
Dependencies:
  hard: zsh, python3, dconf, gnome-extensions, gnome-shell
  install-ego: curl, unzip (or gnome-extensions install)
  install-jcrussell: make, node (>=20), npm, gettext (msgfmt), glib-compile-schemas
  check-updates: git, curl (for EGO)
EOF
}

# --- Theme / CSS (jcrussell stores colors in stylesheet, not gsettings) ---

forge_css_tag() {
  # ThemeManagerBase.cssTag in installed extension, else this repo
  local f
  for f in \
    "$FORGE_EXT_DIR/lib/shared/theme.js" \
    "$FORGE_REPO_ROOT/lib/shared/theme.js" \
    "$FORGE_REPO_ROOT/temp/lib/shared/theme.js"
  do
    if [[ -f "$f" ]]; then
      local tag
      tag=$(grep -oE 'cssTag = [0-9]+' "$f" 2>/dev/null | head -1 | grep -oE '[0-9]+' || true)
      if [[ -n "$tag" ]]; then
        print -r -- "$tag"
        return 0
      fi
    fi
  done
  print -r -- "38" # known jcrussell tag as of v49-90-beta.2
}

forge_stamp_css_last_update() {
  # Set css-last-update == ThemeManager cssTag so enable()/patchCss will NOT
  # overwrite ~/.config/forge/stylesheet/forge/stylesheet.css with defaults.
  forge_need_cmd gsettings
  local tag sd
  tag=$(forge_css_tag)
  sd=$(forge_schema_dir) || forge_die "no schemas dir for stamping css-last-update"
  GSETTINGS_SCHEMA_DIR="$sd" gsettings set "$FORGE_SCHEMA_MAIN" css-last-update "$tag"
  forge_ok "css-last-update → $tag (prevents patchCss clobber)"
}

forge_user_stylesheet_path() {
  print -r -- "$FORGE_CONFIG_DIR/stylesheet/forge/stylesheet.css"
}

# Pick best stylesheet source from a backup dir (stdout = path or empty).
forge_backup_stylesheet_candidate() {
  local bak="$1"
  local c
  for c in \
    "$bak/config/stylesheet/forge/stylesheet.css" \
    "$bak/stylesheet/forge/stylesheet.css" \
    "$bak/stylesheet-custom-pre-jcrussell.css" \
    "$bak/config/stylesheet/forge/stylesheet.css.bak"
  do
    if [[ -f "$c" && -s "$c" ]]; then
      print -r -- "$c"
      return 0
    fi
  done
  return 1
}

# Extract EGO-era border colors from a dconf dump or gsettings text file.
# Prints: focus_color|focus_size|split_color  (empty fields if missing)
forge_extract_ego_colors() {
  local src="$1"
  [[ -f "$src" ]] || return 1
  python3 - "$src" <<'PY'
import re, sys
from pathlib import Path
text = Path(sys.argv[1]).read_text()
def grab(key):
    # dconf: key=value  or gsettings list-recursively: schema key value
    m = re.search(rf"(?:^|\s){re.escape(key)}\s+(?:uint32\s+)?(.+)$", text, re.M)
    if m:
        return m.group(1).strip().strip("'\"")
    m = re.search(rf"^{re.escape(key)}=(.+)$", text, re.M)
    if m:
        return m.group(1).strip().strip("'\"")
    return ""
focus = grab("focus-border-color")
size = grab("focus-border-size")
if size.startswith("uint32"):
    size = size.split()[-1]
split = grab("split-border-color")
print(f"{focus}|{size}|{split}")
PY
}

# Apply EGO gsettings colors into a stylesheet file (in-place or to out path).
# Only touches tiled/focus + split palette rules.
forge_apply_ego_colors_to_css() {
  local css_in="$1" css_out="$2" focus_color="$3" focus_size="$4" split_color="$5"
  python3 - "$css_in" "$css_out" "$focus_color" "$focus_size" "$split_color" <<'PY'
import re, sys
from pathlib import Path
src, dst, focus, size, split = sys.argv[1:6]
text = Path(src).read_text()

def set_rule_props(css, selector, props):
    # props: dict property -> value (already formatted)
    pat = re.compile(
        rf"({re.escape(selector)}\s*\{{)(.*?)(\n\}})",
        re.S,
    )
    m = pat.search(css)
    if not m:
        return css
    body = m.group(2)
    for prop, val in props.items():
        if not val:
            continue
        if re.search(rf"{re.escape(prop)}\s*:", body):
            body = re.sub(rf"({re.escape(prop)}\s*:\s*)[^;]+;", rf"\g<1>{val};", body, count=1)
        else:
            body = body.rstrip() + f"\n  {prop}: {val};\n"
    return css[: m.start()] + m.group(1) + body + m.group(3) + css[m.end() :]

if focus:
    text = set_rule_props(text, ".tiled", {"color": focus, "border-width": f"{size}px" if size else ""})
    text = set_rule_props(
        text,
        ".window-tiled-border",
        {"border-color": focus, "border-width": f"{size}px" if size else ""},
    )
if split:
    text = set_rule_props(text, ".split", {"color": split})
    text = set_rule_props(text, ".window-split-border", {"border-color": split})

Path(dst).parent.mkdir(parents=True, exist_ok=True)
Path(dst).write_text(text)
print(dst)
PY
}

# Restore theme colors from a backup after install/enable.
# Order: restore user stylesheet → optional EGO color patch → stamp css-last-update.
forge_restore_theme_from_backup() {
  local bak="$1"
  local dest dest_dir css_src ego_src focus size split tag

  dest=$(forge_user_stylesheet_path)
  dest_dir="${dest:h}"
  mkdir -p "$dest_dir"

  css_src=""
  if css_src=$(forge_backup_stylesheet_candidate "$bak"); then
    forge_info "stylesheet from backup: $css_src"
    # Keep a safety copy of whatever is live now
    if [[ -f "$dest" ]]; then
      cp -a "$dest" "${dest}.pre-restore-$(forge_stamp)" 2>/dev/null || true
    fi
    cp -a "$css_src" "$dest"
    forge_ok "restored stylesheet → $dest"
  else
    forge_warn "no stylesheet in backup; will try EGO gsettings colors only"
    # Seed from extension default if missing
    if [[ ! -f "$dest" && -f "$FORGE_EXT_DIR/stylesheet.css" ]]; then
      cp -a "$FORGE_EXT_DIR/stylesheet.css" "$dest"
    fi
  fi

  # If backup still has EGO color keys (in dconf dump or gsettings txt), merge them
  # into CSS when the restored file still has stock red focus (common first-run).
  ego_src=""
  [[ -f "$bak/gsettings-forge.txt" ]] && ego_src="$bak/gsettings-forge.txt"
  [[ -z "$ego_src" && -f "$bak/dconf-forge.conf" ]] && ego_src="$bak/dconf-forge.conf"
  if [[ -n "$ego_src" && -f "$dest" ]]; then
    IFS='|' read -r focus size split <<<"$(forge_extract_ego_colors "$ego_src" || true)"
    if [[ -n "$focus" || -n "$split" ]]; then
      # Only merge EGO gsettings colors when the *border* still looks stock.
      # Do not grep the whole file: many themes leave `.tiled { color: red }`
      # palette stubs while customizing `.window-tiled-border` only.
      border_color=$(python3 - "$dest" <<'PY'
import re, sys
from pathlib import Path
text = Path(sys.argv[1]).read_text()
m = re.search(r"\.window-tiled-border\s*\{([^}]*)\}", text, re.S)
if not m:
    print("")
    raise SystemExit
body = m.group(1)
cm = re.search(r"border-color\s*:\s*([^;]+);", body)
print(cm.group(1).strip() if cm else "")
PY
)
      # Stock jcrussell / EGO default focus border
      if [[ "$border_color" == *"236, 94, 94"* || "$border_color" == *"236,94,94"* ]]; then
        forge_info "merging EGO gsettings colors (stock focus border: $border_color)"
        forge_apply_ego_colors_to_css "$dest" "$dest" "$focus" "$size" "$split" >/dev/null
        forge_ok "EGO colors applied (focus=${focus:-none} size=${size:-?} split=${split:-none})"
      else
        forge_info "custom focus border already set ($border_color) — skip EGO gsettings color merge"
      fi
    fi
  fi

  [[ -f "$dest" ]] || forge_warn "no stylesheet at $dest after restore"
  forge_stamp_css_last_update
}
