#!/usr/bin/env zsh
# Safe migrate EGO/SweetTooth → this tree: build BEFORE uninstall.
emulate -L zsh
set -euo pipefail
SCRIPT_DIR=${0:A:h}
source "$SCRIPT_DIR/_lib.zsh"

usage() {
  cat <<EOF
${c_bold}migrate-from-ego.zsh${c_reset} — migrate extensions.gnome.org Forge → this tree

Pipeline (order matters):
  1. save-settings           extension + dconf + ~/.config/forge
  2. preflight               backup non-empty; translate keeps keys
  3. build-install --build-only   build temp/ while old Forge still installed
  4. write emergency-rollback.sh into the backup
  5. uninstall               extension code only (never purges dconf/config)
  6. build-install --install-only
  7. apply-settings --translate=jcrussell  (dconf + CSS + stamp css-last-update)
  8. enable
  9. restore-theme again (belt-and-suspenders; patchCss no longer clobbers user CSS)
 10. reload Shell on X11 (default) so the new build is active

Prefer root ${c_blue}./install${c_reset} (same path when lineage is EGO).

Usage:
  migrate-from-ego.zsh [options]

Options:
  --repo=PATH        this tree (default: parent of scripts/)
  --prod             production build (default: dev/debug)
  --skip-save        Use latest backup
  --skip-apply       Leave dconf as-is after install
  --skip-build       Use existing repo temp/ (must already be built)
  --restart-shell    X11 HUP after enable (default)
  --no-restart       Do not HUP gnome-shell
  --name=LABEL       Backup label
  --force            Non-interactive
  --color=auto|always|never
  -h, --help

Rollback:
  \$BACKUP/emergency-rollback.zsh
  or: $SCRIPT_DIR/rollback.zsh \$BACKUP

$(forge_print_deps_help)
EOF
}

MODE_ARGS=()
SKIP_SAVE=0
SKIP_APPLY=0
SKIP_BUILD=0
RESTART_SHELL=1
NAME=""
forge_parse_common_args "$@"
if (( ${#FORGE_ARGS[@]} > 0 )); then
  set -- "${FORGE_ARGS[@]}"
else
  set --
fi
[[ "${FORGE_WANT_HELP:-0}" == "1" ]] && { usage; exit 0; }

while (( $# )); do
  case "$1" in
    --prod) MODE_ARGS+=(--prod); shift ;;
    --skip-save) SKIP_SAVE=1; shift ;;
    --skip-apply) SKIP_APPLY=1; shift ;;
    --skip-build) SKIP_BUILD=1; shift ;;
    --restart-shell) RESTART_SHELL=1; shift ;;
    --no-restart|--no-restart-shell) RESTART_SHELL=0; shift ;;
    --name=*) NAME="${1#--name=}"; shift ;;
    --name) NAME="${2:?}"; shift 2 ;;
    -*) forge_die "unknown option: $1" ;;
    *) forge_die "unexpected arg: $1" ;;
  esac
done

export FORGE_FORCE="${FORGE_FORCE:-0}"

forge_hdr "Migrate EGO → this tree"
forge_info "current lineage: $(forge_detect_lineage)"
forge_info "repo: $FORGE_REPO_ROOT"
forge_info "session: $(forge_session_type)"

if ! forge_confirm "Save, build, replace extension with this tree, re-apply settings?"; then
  forge_die "aborted"
fi
export FORGE_FORCE=1

live_keys=0
if command -v dconf >/dev/null 2>&1; then
  live_keys=$(dconf dump "$FORGE_DCONF_PATH" 2>/dev/null | grep -c '=' || true)
fi
forge_info "live dconf keys before switch: $live_keys"
dconf dump "$FORGE_DCONF_PATH" >"/tmp/forge-switch-live-$$.conf" 2>/dev/null || true

BACKUP=""
if (( ! SKIP_SAVE )); then
  label="${NAME:-migrate-ego-$(forge_stamp)}"
  BACKUP=$("$SCRIPT_DIR/save-settings.zsh" --name="$label" --force)
  BACKUP="${BACKUP//$'\n'/}"
  forge_ok "backup: $BACKUP"
else
  BACKUP=$(forge_latest_backup) || forge_die "--skip-save but no backups found"
  forge_info "using existing backup: $BACKUP"
fi

# --- Preflight backup ---
[[ -d "$BACKUP" ]] || forge_die "backup dir missing: $BACKUP"
[[ -f "$BACKUP/dconf-forge.conf" && -s "$BACKUP/dconf-forge.conf" ]] \
  || forge_die "backup dconf missing/empty — aborting"
bak_keys=$(grep -c '=' "$BACKUP/dconf-forge.conf" || true)
if (( live_keys > 0 && bak_keys == 0 )); then
  forge_die "live has $live_keys dconf keys but backup has 0 — aborting"
fi
if (( live_keys > 0 && bak_keys < live_keys )); then
  forge_die "backup has fewer keys ($bak_keys) than live ($live_keys) — aborting"
fi
"$SCRIPT_DIR/translate-settings.zsh" --to=jcrussell \
  "$BACKUP/dconf-forge.conf" "$BACKUP/dconf-preflight.conf" >/dev/null
pre_keys=$(grep -c '=' "$BACKUP/dconf-preflight.conf" || true)
if (( bak_keys > 0 && pre_keys == 0 )); then
  forge_die "translate would drop all $bak_keys keys — aborting"
fi
if (( bak_keys > 0 && pre_keys * 2 < bak_keys )); then
  forge_die "translate would keep only $pre_keys of $bak_keys keys — aborting"
fi
forge_ok "preflight OK: backup $bak_keys keys → translate keeps $pre_keys"

# --- Build FIRST (old extension still installed) ---
if (( ! SKIP_BUILD )); then
  forge_hdr "Build this tree (before uninstall — safe if build fails)"
  "$SCRIPT_DIR/build-install.zsh" --force --build-only --no-enable "${MODE_ARGS[@]}"
else
  forge_info "skip-build: verifying existing temp/"
  [[ -f "$FORGE_REPO_ROOT/temp/extension.js" ]] || forge_die "no temp/ build; omit --skip-build"
fi

# Emergency rollback helper in the backup itself
cat >"$BACKUP/emergency-rollback.zsh" <<EOF
#!/usr/bin/env zsh
# Auto-generated by migrate-from-ego — restore EGO (or prior) extension + settings
emulate -L zsh
set -euo pipefail
BACKUP="$BACKUP"
EXT="$FORGE_EXT_DIR"
print "Rolling back Forge from \$BACKUP"
gnome-extensions disable forge@jmmaranan.com 2>/dev/null || true
rm -rf "\$EXT"
cp -a "\$BACKUP/extension" "\$EXT"
dconf load /org/gnome/shell/extensions/forge/ < "\$BACKUP/dconf-forge.conf"
if [[ -d "\$BACKUP/config" ]]; then
  mkdir -p "\$HOME/.config/forge"
  cp -a "\$BACKUP/config"/. "\$HOME/.config/forge"/
fi
print "Restored. Restart GNOME Shell / log out, then:"
print "  gnome-extensions enable forge@jmmaranan.com"
EOF
chmod +x "$BACKUP/emergency-rollback.zsh"
forge_ok "emergency rollback: $BACKUP/emergency-rollback.zsh"

# --- Uninstall code only ---
"$SCRIPT_DIR/uninstall.zsh" --force

mid_keys=$(dconf dump "$FORGE_DCONF_PATH" 2>/dev/null | grep -c '=' || true)
forge_info "dconf keys after uninstall: $mid_keys (should be $live_keys)"
if (( live_keys > 0 && mid_keys == 0 )); then
  forge_die "dconf wiped after uninstall — run $BACKUP/emergency-rollback.zsh"
fi

# --- Install pre-built temp/ ---
"$SCRIPT_DIR/build-install.zsh" --force --install-only --no-enable "${MODE_ARGS[@]}"

case "$(forge_detect_lineage)" in
  jcrussell|luke) ;;
  *)
    forge_warn "lineage not luke/jcrussell after install — check $FORGE_EXT_DIR/metadata.json"
    ;;
esac

if (( ! SKIP_APPLY )); then
  "$SCRIPT_DIR/apply-settings.zsh" --force --translate=jcrussell "$BACKUP"
  post_keys=$(dconf dump "$FORGE_DCONF_PATH" 2>/dev/null | grep -c '=' || true)
  forge_info "dconf keys after apply: $post_keys"
  if (( pre_keys > 0 && post_keys < pre_keys )); then
    forge_warn "post-apply key count $post_keys < expected $pre_keys — reloading raw backup"
    dconf load "$FORGE_DCONF_PATH" <"$BACKUP/dconf-forge.conf"
  fi
  # Value-level check ignoring runtime stamps
  if [[ -f "/tmp/forge-switch-live-$$.conf" ]]; then
    python3 - "/tmp/forge-switch-live-$$.conf" <(dconf dump "$FORGE_DCONF_PATH") <<'PY' || {
import sys
from pathlib import Path

def parse(text):
    section = "/"
    out = {}
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("[") and s.endswith("]"):
            section = s[1:-1]
            continue
        if "=" in s:
            k, v = s.split("=", 1)
            out[(section, k.strip())] = v.strip()
    return out

ignore = {
    ("/", "css-last-update"),
    ("/", "css-updated"),
    ("/", "config-last-import"),
    ("/", "config-last-export"),
}
before = parse(Path(sys.argv[1]).read_text())
after = parse(Path(sys.argv[2]).read_text())
bad = []
for k, v in before.items():
    if k in ignore:
        continue
    if k not in after:
        bad.append(f"missing {k}")
    elif after[k] != v:
        bad.append(f"changed {k}: {v!r} -> {after[k]!r}")
if bad:
    print("SETTINGS DRIFT:", *bad, sep="\n  ")
    sys.exit(1)
print(f"OK user settings preserved ({len(before)} keys in baseline)")
PY
      forge_warn "settings drift detected — reloading raw backup dconf"
      dconf load "$FORGE_DCONF_PATH" <"$BACKUP/dconf-forge.conf"
    }
  fi
else
  forge_info "skipped apply; dconf left as-is ($mid_keys keys)"
fi

gnome-extensions enable "$FORGE_UUID" 2>/dev/null \
  || forge_warn "enable deferred — restart shell then: gnome-extensions enable $FORGE_UUID"

# Drop rival GNOME Shell tilers (Tiling Assistant, Pop Shell, …). Not i3/sway.
_mig_rivals=()
while IFS= read -r _mig_line; do
  [[ -n "$_mig_line" ]] && _mig_rivals+=("$_mig_line")
done < <(forge_disable_rival_tilers)
if (( ${#_mig_rivals[@]} > 0 )); then
  forge_ok "disabled rival tilers: ${(j:, :)_mig_rivals}"
fi
unset _mig_rivals _mig_line

# Re-restore user CSS after enable (belt-and-suspenders; patchCss no longer
# overwrites user overrides with bundled defaults).
if (( ! SKIP_APPLY )); then
  forge_hdr "Re-restore theme after enable"
  forge_restore_theme_from_backup "$BACKUP"
fi

# Host chords (lock Super+Delete, quit Super+q, maximize Super+Return, …)
if [[ -f "$SCRIPT_DIR/host-defaults.conf" ]]; then
  forge_hdr "Apply host keyboard defaults"
  "$SCRIPT_DIR/apply-host-defaults.zsh" --force "$SCRIPT_DIR/host-defaults.conf"
fi

if (( RESTART_SHELL )); then
  rc=0
  forge_restart_shell || rc=$?
  if (( rc == 0 )); then
    sleep 1
    gnome-extensions enable "$FORGE_UUID" 2>/dev/null || true
    forge_disable_rival_tilers >/dev/null || true
    # One more theme pass after HUP enable
    if (( ! SKIP_APPLY )); then
      forge_restore_theme_from_backup "$BACKUP"
    fi
    if [[ -f "$SCRIPT_DIR/host-defaults.conf" ]]; then
      "$SCRIPT_DIR/apply-host-defaults.zsh" --force "$SCRIPT_DIR/host-defaults.conf"
    fi
  elif (( rc == 2 )); then
    forge_warn "--restart-shell needs logout on this session type"
  fi
else
  forge_warn "Shell not reloaded (--no-restart). Files are installed; reload to activate."
  forge_warn "X11: killall -HUP gnome-shell  |  Wayland: log out/in  |  $SCRIPT_DIR/status.zsh"
  forge_warn "If colors look stock: $SCRIPT_DIR/restore-theme.zsh $BACKUP && Super+Shift+r"
fi

rm -f "/tmp/forge-switch-live-$$.conf"
forge_write_install_origin "$FORGE_REPO_ROOT" git || \
  forge_warn "could not write install-origin (non-fatal)"
forge_ok "migrate-from-ego complete (lineage=$(forge_detect_lineage))"
forge_ok "backup + rollback: $BACKUP"
print -r -- "$BACKUP"
