// @ts-check
/**
 * Shared OpSet / query action ids (dotted). Not window-move-left / opset:move:left.
 * size.float* = set size to share (D090); ids stay until a rename.
 */

export const ACTIONS = Object.freeze([
  "focus.left",
  "focus.down",
  "focus.up",
  "focus.right",
  "focus.parent",
  "focus.child",
  "move.left",
  "move.down",
  "move.up",
  "move.right",
  "join.left",
  "join.down",
  "join.up",
  "join.right",
  "toggleSplit",
  "toggleTabStack",
  "layout.cycle-",
  "layout.cycle+",
  "promote",
  "promoteRecursive",
  "remove",
  "launch",
  "size.nudge.x-",
  "size.nudge.x+",
  "size.nudge.y-",
  "size.nudge.y+",
  "size.float",
  "size.floatSiblings",
  "size.floatSiblingsOnly",
  "size.floatSelfSiblingsParent",
  "size.floatParent",
  "size.floatParentGroup",
  "size.floatParentSiblingsOnly",
  "size.floatBothGroups",
  "size.floatAll",
  "size.preset.7",
  "size.preset.8",
  "size.preset.9",
  "size.preset.0",
]);

export const ACTION_SET = new Set(ACTIONS);

export const ACTION_LABELS = Object.freeze({
  "focus.left": "Focus left",
  "focus.down": "Focus down",
  "focus.up": "Focus up",
  "focus.right": "Focus right",
  "focus.parent": "Focus parent",
  "focus.child": "Focus child",
  "move.left": "Move left",
  "move.down": "Move down",
  "move.up": "Move up",
  "move.right": "Move right",
  "join.left": "Join left",
  "join.down": "Join down",
  "join.up": "Join up",
  "join.right": "Join right",
  toggleSplit: "Toggle split",
  toggleTabStack: "Toggle tab/stack",
  "layout.cycle-": "Cycle layout previous",
  "layout.cycle+": "Cycle layout next",
  promote: "Promote children",
  promoteRecursive: "Promote recursive",
  remove: "OpSet remove (with settle)",
  launch: "Launch (selected)",
  "size.nudge.x-": "Decrease x share",
  "size.nudge.x+": "Increase x share",
  "size.nudge.y-": "Decrease y share",
  "size.nudge.y+": "Increase y share",
  "size.float": "Size: share",
  "size.floatSiblings": "Size: share (this and siblings)",
  "size.floatSiblingsOnly": "Size: share (siblings only)",
  "size.floatSelfSiblingsParent": "Size: share (this, siblings, parent)",
  "size.floatParent": "Size: share (parent)",
  "size.floatParentGroup": "Size: share (parent group)",
  "size.floatParentSiblingsOnly": "Size: share (parent siblings)",
  "size.floatBothGroups": "Size: share (both groups)",
  "size.floatAll": "Size: share (all)",
  "size.preset.7": "In-axis 75%",
  "size.preset.8": "In-axis 66.7%",
  "size.preset.9": "In-axis 50%",
  "size.preset.0": "In-axis 33.3%",
});
